{{- if $.Values.cloud.haproxyIngressController.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ index $.Values "hedera-explorer" "ingress" "className" }}
spec:
  controller: haproxy-ingress.github.io/controller
{{- end }}