{{- if $.Values.cloud.haproxyIngressController.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ required "$.Values.global.ingressClassName is required" $.Values.global.ingressClassName }}
spec:
  controller: haproxy-ingress.github.io/controller
{{- end }}