apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-operator.fullname" . }}-prometheus-operator
  labels:
    app.kubernetes.io/component: controller
  {{- include "prometheus-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheusOperator.type }}
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
  {{- include "prometheus-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.prometheusOperator.ports | toYaml | nindent 2 -}}