# Configmap contains data: "data"
apiVersion: v1
kind: ConfigMap
metadata:
  name: hedera-mirror-explorer-networks-config
data:
  #Empty multi line json
  networks-config.json: |
    [
      {
        "name": "mainnet",
        "displayName": "MAINNET",
        "url": "https://mainnet-public.mirrornode.hedera.com/",
        "ledgerID": "00"
      },
      {
        "name": "testnet",
        "displayName": "TESTNET",
        "url": "https://testnet.mirrornode.hedera.com/",
        "ledgerID": "01"
      },
      {
        "name": "previewnet",
        "displayName": "PREVIEWNET",
        "url": "https://previewnet.mirrornode.hedera.com/",
        "ledgerID": "02"
      },
      {
        "name": "local",
        "displayName": "LOCALNET",
        "url": "http://127.0.0.1:9000/",
        "ledgerID": "03"
      }
    ]
