apiVersion: v2
name: fullstack-cluster-setup
description: A Helm chart to setup shared resources for fullstack-testing

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.12.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.12.0"

dependencies:
  - name: operator
    alias: minio-operator
    version: 5.0.7
    repository: https://operator.min.io/
    condition: cloud.minio.enabled

  - name: kube-prometheus-stack
    alias: prometheus-stack
    version: 52.0.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: cloud.prometheusStack.enabled

  - name: grafana-agent
    version: 0.27.1
    repository: https://grafana.github.io/helm-charts
    condition: cloud.grafanaAgent.enabled

  - name: gateway-helm
    alias: envoy-gateway
    version: v0.5.0
    repository: oci://docker.io/envoyproxy
    condition: cloud.envoyGateway.enabled

  - name: cert-manager
    version: v1.13.2
    repository: https://charts.jetstack.io
    condition: cloud.certManager.enabled