version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
