apiVersion: v1
kind: Secret
metadata:
  name: uploader-mirror-secrets
type: Opaque
data:
  # TODO: use helm variables here
  S3_ACCESS_KEY: "bWluaW8K"
  S3_SECRET_KEY: "bWluaW8xMjMK"
  GCS_ACCESS_KEY: "bWluaW8K"
  GCS_SECRET_KEY: "bWluaW8xMjMK"
