{{- $minio_accessKey := randAlpha 10  -}}
{{- $minio_secretKey := randAlpha 10  -}}
{{- $minio_config_env := printf "export MINIO_ROOT_USER=%s\nexport MINIO_ROOT_PASSWORD=%s" $minio_accessKey $minio_secretKey -}}

apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
type: Opaque
data:
  config.env: {{ $minio_config_env | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: uploader-mirror-secrets
type: Opaque
data:
  S3_ACCESS_KEY: {{ $minio_accessKey | b64enc }}
  S3_SECRET_KEY: {{ $minio_secretKey | b64enc }}