# cloud configuration
cloud:
  buckets:
    streamBucket: fst-streams
    backupBucket: fst-backups
  s3:
    enabled: true
  gcs:
    enabled: true

# reduce default termination grace period
terminationGracePeriodSeconds: 10

# hedera node configuration
hedera:
  nodes:
    - name: node0
      resources:
        requests:
          cpu: 100m
          memory: 1G
        limits:
          cpu: 100m
          memory: 1G
      root:
        image:
          registry: ghcr.io
          repository: hashgraph/full-stack-testing/ubi8-init-dind
          tag: "0.3.0"  # Defaults to the chart's app version if empty
          pullPolicy: IfNotPresent
      haproxy:
        image:
          registry: docker.io
          repository: haproxy
          tag: "2.4-alpine"  # Defaults to the chart's app version if empty
          pullPolicy: IfNotPresent
        replica: 1
      envoyProxy:
        image:
          registry: docker.io
          repository: envoyproxy/envoy
          tag: "v1.21.1"  # Defaults to the chart's app version if empty
          pullPolicy: IfNotPresent
        replica: 1
      sidecars:
        recordStreamUploader:
          enabled: true
          nameOverride: "record-stream-uploader"
          image:
            registry: gcr.io
            repository: hedera-registry/uploader-mirror
            tag: "1.3.0"  # Defaults to the chart's app version if empty
            pullPolicy: IfNotPresent
          config:
            debug: true
            compression: true
            sidecar: true
            reaper:
              enable: true
              minKeep: 1
              interval: 1
              defaultBackoff: 1
            signature:
              require: true
              prioritize: true
        eventStreamUploader:
          enabled: true
          nameOverride: "event-stream-uploader"
          image:
            registry: gcr.io
            repository: hedera-registry/uploader-mirror
            tag: "1.3.0"  # Defaults to the chart's app version if empty
            pullPolicy: IfNotPresent
          config:
            debug: true
            compression: true
            reaper:
              enable: true
              minKeep: 1
              interval: 1
              defaultBackoff: 1
            signature:
              require: true
              prioritize: true
        accountBalanceUploader:
          enabled: true
          nameOverride: "account-balance-uploader"
          image:
            registry: gcr.io
            repository: hedera-registry/uploader-mirror
            tag: "1.3.0"  # Defaults to the chart's app version if empty
            pullPolicy: IfNotPresent
          config:
            debug: true
            compression: true
            reaper:
              enable: true
              minKeep: 1
              interval: 1
              defaultBackoff: 1
            signature:
              require: true
              prioritize: true
        backupUploader:
          enabled: true
          nameOverride: "backup-uploader"
          image:
            registry: gcr.io
            repository: "hedera-registry/hedera-backups"
            tag: "0.6.0"
            pullPolicy: IfNotPresent
          config:
            backupBucket: "backup"
        otelCollector:
          enabled: true
          nameOverride: "otel-collector"
          image:
            registry: docker.io
            repository: "otel/opentelemetry-collector-contrib"
            tag: "0.72.0"
            pullPolicy: IfNotPresent
#          resources:
#            requests:
#              cpu: 100m
#              memory: 1G
#            limits:
#              cpu: 100m
#              memory: 1G
          config: {}
