{{- if $.Values.cloud.selfSignedClusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed
  namespace: cert-manager
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "2"
spec:
  selfSigned: {}
{{- end }}