apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuers.staging.name }}
  namespace: cert-manager
  {{- with .Values.issuers.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.issuers.staging.email }}
    privateKeySecretRef:
      name: {{ .Values.issuers.staging.name }}
    solvers:
      {{- if .Values.solvers.http01.enabled }}
      - http01:
          {{- if .Values.solvers.http01.solverType | eq "ingress" }}
          ingress:
            {{- with .Values.solvers.http01.ingress }}
            name: {{ .name }}
            class: {{ $.Values.global.ingressClassName | default .class }}
            serviceType: {{ .serviceType }}
            {{- end }}
          {{- end }}
          {{- if .Values.solvers.http01.solverType | eq "gatewayHTTPRoute" }}
          gatewayHTTPRoute:
            {{- with .Values.solvers.http01.gatewayHTTPRoute }}
            parentRefs:
              - name: {{ .name }}
                namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
                kind: Gateway
            {{- end }}
          {{- end }}
      {{- end }}
