receivers:
  otlp:
    protocols:
      grpc:
      http:

  # Collect node metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'node-metrics-scraper' # network-node metrics
          scrape_interval: 5s # TODO make scrape interval configurable
          static_configs:
            - targets: [ '0.0.0.0:9999' ] # TODO make the node metrics port configurable

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889" # note: network-node-svc exposes this port for prometheus metrics instead of node's port 9999
    const_labels:
      source: p-{{ default "otel-collector" .otelDefaults.nameOverride }} # PromQL: {source="p-otel-collector"}
  {{- if eq .otelDefaults.prometheusRemoteWrite.enable "true" }}
  prometheusremotewrite:
    endpoint: "{{ .otelDefaults.prometheusRemoteWrite.endpoint }}"
    tls:
      insecure: true
    external_labels:
      source: prw-{{ default "otel-collector" .otelDefaults.nameOverride }} # PromQL: {source="prw-otel-collector"}
  {{- end }}

#  logging:
#    verbosity: detailed
#    sampling_initial: 5

#  otlp:
#    endpoint: ""
#    tls:
#      insecure: true

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
#    traces:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [otlp]

    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters:
        - prometheus
        {{- if eq .otelDefaults.prometheusRemoteWrite.enable "true" }}
        - prometheusremotewrite
        {{- end }}
