receivers:
  otlp:
    protocols:
      grpc:
  hostmetrics:
    collection_interval: "15s"
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: "{{ .defaults.sidecars.otelCollector.nameOverride }}-label1"

  logging:

#  jaeger:
#    endpoint: jaeger-all-in-one:14250
#    tls:
#      insecure: true
#
#  otlp:
#    endpoint: tempo:4317
#    tls:
#      insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    #traces:
    #  receivers: [otlp]
    #  processors: [batch]
    #  exporters: [logging, otlp, jaeger]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [logging, prometheus]
