apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-monitoring-role
  namespace: {{ include "fullstack.namespace" $ }}
rules:
  - apiGroups: [ "" ]
    resources:
      - pods
      - pods/log
      - secrets
    verbs:
      - get
      - list
  - apiGroups: [ "" ]
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups: [ "gateway.networking.k8s.io" ]
    resources:
      - gatewayclasses
      - gateways
      - httproutes
      - tcproutes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-monitoring-role-binding
  namespace: {{ include "fullstack.namespace" $ }}
subjects:
  - kind: ServiceAccount
    name: pod-monitor
    namespace: {{ include "fullstack.namespace" $ }}
roleRef:
  kind: ClusterRole
  name: pod-monitoring-role
  apiGroup: rbac.authorization.k8s.io
