apiVersion: v1
kind: ServiceAccount
metadata:
  name: tester
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tester-role
rules:
  - apiGroups: [ "" ]
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
  - apiGroups: [ "" ]
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tester-role-binding
subjects:
  - kind: ServiceAccount
    name: tester
roleRef:
  kind: Role
  name: tester-role
  apiGroup: rbac.authorization.k8s.io
