apiVersion: v1
kind: Secret
metadata:
  name: backup-uploader-secrets
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
type: Opaque
data:
  S3_ACCESS_KEY: ""
  S3_SECRET_KEY: ""
  GCS_ACCESS_KEY: ""
  GCS_SECRET_KEY: ""
