{{- $password := include "generateHaproxyPassword" . -}}
{{- $username := include "generateHaproxyUser" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: haproxy-secrets
type: Opaque
data:
  haproxy_user: {{ $username }}
  haproxy_password: {{ $password }}
---
