{{- $namespace := default $.Release.Namespace $.Values.global.namespaceOverride }}
{{- $previous := lookup "v1" "Secret" $namespace "haproxy-secrets" }}
apiVersion: v1
kind: Secret
metadata:
  name: haproxy-secrets
  namespace: {{ $namespace }}
type: Opaque
stringData:
{{- if ((($previous).data).HAPROXY_USERNAME) }}
  HAPROXY_USERNAME: {{ b64dec $previous.data.HAPROXY_USERNAME }}
{{- else }}
  HAPROXY_USERNAME: {{ randAlpha 7 }}
{{- end }}
{{- if ((($previous).data).HAPROXY_PASSWORD) }}
  HAPROXY_PASSWORD: {{ b64dec $previous.data.HAPROXY_PASSWORD }}
{{- else }}
  HAPROXY_PASSWORD: {{ randAlpha 10 }}
{{- end }}
---
