{{ range $index, $node := ($.Values.hedera.nodes) }}
{{- $envoyProxy := $node.envoyProxy | default $.Values.defaults.envoyProxy -}}
{{- $defaults := $.Values.defaults.envoyProxy }}
{{- if $envoyProxy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy-{{ $node.name }}-svc
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    fullstack.hedera.com/type: envoy-proxy-svc
    fullstack.hedera.com/node-name: {{ $node.name }}
    fullstack.hedera.com/account-id: {{ $node.accountId }}
    fullstack.hedera.com/prometheus-endpoint: active
    {{- include "fullstack.testLabels" $ | nindent 4 }}
spec:
  {{- if $envoyProxy.loadBalancerEnabled }}
  type: LoadBalancer
  {{- end }}
  selector:
    app: envoy-proxy-{{ $node.name }}
  ports:
    - name: hedera-grpc-web
      port: 8080
      targetPort: 8080 # hedera-grpc-web-listener port
    - name: prometheus # port name must be prometheus for prometheus-svc-monitor
      port: 9090
      targetPort: 9090 # envoy-proxy's prometheus-listener port
{{- end }}
{{- end }}

