{{- if $.Values.cloud.selfSignedClusterIssuer.enabled }}
{{- if index $.Values "hedera-explorer" "enabled" | eq true }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-secret-hedera-explorer
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
spec:
  isCA: false
  commonName: {{ $.Values.deployment.hederaExplorer.hostname }}
  dnsNames:
    - {{ $.Values.deployment.hederaExplorer.hostname }}
  secretName: ca-secret-hedera-explorer
  privateKey:
    algorithm: RSA
    size: 3072
  issuerRef:
    name: fst-self-signed-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
{{- end }}
