{{- if $.Values.cloud.selfSignedClusterIssuer.enabled }}
{{/*{{- if $.Values.gatewayApi.gateway.listeners.hederaExplorer.tlsEnabled }}*/}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
{{/*  name: {{ $.Values.gatewayApi.gateway.tlsClusterIssuerName }}-ca-secret-hedera-explorer*/}}
  name: self-signed-ca-secret-hedera-explorer
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
spec:
  isCA: false
  commonName: {{ $.Values.deployment.hederaExplorer.hostname }}
  dnsNames:
    - {{ $.Values.deployment.hederaExplorer.hostname }}
{{/*  secretName: {{ $.Values.gatewayApi.gateway.tlsClusterIssuerName }}-ca-secret-hedera-explorer*/}}
  secretName: self-signed-ca-secret-hedera-explorer
  privateKey:
    algorithm: RSA
    size: 3072
  issuerRef:
{{/*    name: {{ $.Values.gatewayApi.gateway.tlsClusterIssuerName }}*/}}
    name: self-signed
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
