{{- if $.Values.cloud.selfSignedClusterIssuer.enabled }}
{{- if index $.Values "hedera-explorer" "enabled" | eq true }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-secret-hedera-explorer
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
spec:
  isCA: false
  commonName: {{ $.Values.deployment.hederaExplorer.hostname }}
  dnsNames:
    - {{ $.Values.deployment.hederaExplorer.hostname }}
  secretName: ca-secret-hedera-explorer
  privateKey:
    algorithm: RSA
    size: 3072
  issuerRef:
    {{- if index .Values "hedera-explorer" "certClusterIssuerType" | eq "self-signed"}}
    name: {{ tpl (index .Values "hedera-explorer" "selfSignedCertClusterIssuer") . }}
    {{- else if index .Values "hedera-explorer" "certClusterIssuerType" | eq "acme-staging" }}
    name: {{ tpl (index .Values "acme-cluster-issuer" "issuers" "staging" "name") . }}
    {{- else if index .Values "hedera-explorer" "certClusterIssuerType" | eq "acme-prod" }}
    name: {{ tpl (index .Values "acme-cluster-issuer" "issuers" "production" "name") . }}
    {{- end }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
{{- end }}
