[versions]
fabric8-kubernetes = "6.6.2"

[libraries]
kubernetes-client = { group = "io.fabric8", name = "kubernetes-client", version.ref = "fabric8-kubernetes" }

[bundles]
kubernetes = ["kubernetes-client"]
