# Configmaps for envoy one for each network node
# This will change, we plan to only have envoy for a network node only if specified in the config
{{- range $index, $node := ($.Values.hedera.nodes) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-proxy-cm-{{ $node.name }}
  namespace: {{ include "fullstack.namespace" $ }}
data:
  envoy.yaml: |
    {{- tpl ($.Files.Get "config-files/envoy.yaml") (dict "nodeConfig" $node "Template" $.Template) | nindent 4 }}
---
{{ end }}
