# Create a haproxy configmap for each network node
# This will change in the future, we plan create a haproxy for a given network node only if specified in the config
{{- range $index, $node := ($.Values.hedera.nodes) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-cm-{{ $node.name }}
  namespace: {{ default .Release.Namespace .Values.global.namespaceOverride }}
data:
  haproxy.cfg: |
    {{- tpl ($.Files.Get "config-files/haproxy.cfg") (dict "nodeConfig" $node "Template" $.Template) | nindent 4 }}
---
{{ end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ofac-cm
data:
  ofacBlock.acl: |
    {{- .Files.Get "config-files/ofacBlock.acl" | nindent 4  }}
