apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
  namespace: {{ include "fullstack.namespace" $ }}
data:
  {{- $total_nodes := len $.Values.hedera.nodes -}}
  {{- range $path, $_ :=  .Files.Glob  "tests/*.*" }}
  {{ base $path }}: |
  {{- tpl ($.Files.Get $path) ( dict "total_nodes" $total_nodes "Template" $.Template ) | nindent 4 }}
  {{- end }}
