env:
  browser: true
  es2021: true
extends: standard
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  indent: ["error", 2],
  space-before-function-paren: ["error", {
    anonymous: "always",
    named: "never",
    asyncArrow: "always"
  }],
  max-len: ["error", {
    code: 120,
    ignoreComments: true,
    ignoreStrings: true,
    ignoreTemplateLiterals: true,
    ignoreRegExpLiterals: true
  }],
}
overrides:
  - files: ["*.mjs"]
    parserOptions:
      ecmaVersion: latest
      sourceType: module
