apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-shared-pvc
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    fullstack.hedera.com/type: node-shared-pvc
    {{- include "fullstack.testLabels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ default "2Gi" $.Values.defaults.volumeClaims.nodeSharedStorage }}
  storageClassName: standard
# TODO ephemeral shared