{{- if $.Values.gatewayApi.gatewayClass.enable | eq "true" }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: {{ $.Values.gatewayApi.gatewayClass.name }}
  namespace: default
  labels:
    fullstack.hedera.com/type: gateway-class
spec:
  controllerName: haproxy-ingress.github.io/controller
{{- end }}
{{- if $.Values.gatewayApi.gateway.enable | eq "true" }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ $.Values.gatewayApi.gateway.name }}
  namespace: default
  labels:
    fullstack.hedera.com/type: gateway
spec:
  gatewayClassName: {{ $.Values.gatewayApi.gatewayClass.name }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      port: 443
    - name: json-rpc-relay
      protocol: HTTP
      port: 8080
    - name: non-tls-grpc-client-port
      protocol: HTTP
      port: 50211
    - name: tls-grpc-client-port
      protocol: HTTPS
      port: 50212
{{- end }}