{{- if $.Values.gatewayApi.gatewayClass.enable | eq "true" }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: {{ $.Values.gatewayApi.gatewayClass.name }}
  namespace: default
  labels:
    fullstack.hedera.com/type: gateway-class
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
{{- end }}
{{- if $.Values.gatewayApi.gateway.enable | eq "true" }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ $.Values.gatewayApi.gateway.name }}
  namespace: default
  labels:
    fullstack.hedera.com/type: gateway
spec:
  gatewayClassName: {{ $.Values.gatewayApi.gatewayClass.name }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
{{- end }}