{{- if $.Values.gatewayApi.gatewayClass.enable | eq "true" }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: {{ $.Values.gatewayApi.gatewayClass.name }}
  namespace: default
  labels:
    fullstack.hedera.com/type: gateway-class
spec:
  controllerName: {{ $.Values.gatewayApi.gatewayClass.controllerName }}
{{- end }}
{{- if $.Values.gatewayApi.gateway.enable | eq "true" }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ $.Values.gatewayApi.gateway.name }}
  namespace: default
  labels:
    fullstack.hedera.com/type: gateway
spec:
  gatewayClassName: {{ $.Values.gatewayApi.gatewayClass.name }}
  listeners:
    - name: http-debug
      protocol: HTTP
      port: 80
    - name: tcp-debug
      protocol: TCP
      port: 9000
      allowedRoutes:
        kinds:
          - kind: TCPRoute
    - name: grpc-debug
      protocol: TCP
      port: 9090
      allowedRoutes:
        kinds:
          - kind: TCPRoute # we use TCPRoute to for GRPC
    {{- range $index, $node := $.Values.hedera.nodes }} # we assume to have at most 999 nodes in a single cluster
    {{- $gossip_port   := add $index 51000 }} # node0:51000 ... node999: 51999, points to 50111 port in haproxy or network-node
    {{- $grpc_port     := add $index 52000 }} # node0:52000 ... node999: 52999, points to 50211 port in haproxy or network-node
    {{- $grpcs_port    := add $index 53000 }} # node0:53000 ... node999: 53999, points to 50212 port in haproxy or network-node
    {{- $grpc_web_port := add $index 18000 }} # node0:18000 ... node999: 18999, points to 8080 port in envoy proxy
    - name: gossip-{{ $node.name }} # for exposing gossip port 50111 from network-node
      protocol: TCP
      port: {{ $gossip_port }}
      allowedRoutes:
        kinds:
          - kind: TCPRoute
    - name: grpc-{{ $node.name }} # for exposing grpc port 50211 from haproxy or network-node
      protocol: TCP
      port: {{ $grpc_port }}
      allowedRoutes:
        kinds:
          - kind: TCPRoute
    - name: grpcs-{{ $node.name }} # for exposing grpc port 50212 from haproxy or network-node
      protocol: TCP
      port: {{ $grpcs_port }}
      allowedRoutes:
        kinds:
          - kind: TCPRoute
    - name: grpc-web-{{ $node.name }} # for exposing grpc-web port 8080 from envoy-proxy
      protocol: HTTP
      port: {{ $grpc_web_port }}
    {{- end }}
{{- end }}