{{- range $index, $node := ($.Values.hedera.nodes) }}
{{- $haproxy := $node.haproxy | default dict -}}
{{- $defaults := $.Values.defaults.haproxy }}
{{- if default $defaults.enable $haproxy.enable | eq "false" }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ $.Release.Name }}-node-grpc-route-{{ $node.name }}
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    fullstack.hedera.com/type: tcp-route
    fullstack.hedera.com/nodeName: {{ $node.name }}
spec:
  parentRefs:
    - name: {{ $.Values.gatewayApi.gateway.name }}
      sectionName: grpc-{{ $node.name }}
  rules:
    - backendRefs:
      - name: {{ $.Release.Name }}-network-{{ $node.name }}-svc
        port: 50211
{{- end }}
{{- end }}
