{{ range $index, $node := ($.Values.hedera.nodes) }}
{{- $envoyProxy := $node.envoyProxy | default dict -}}
{{- $defaults := $.Values.defaults.envoyProxy }}
{{- if default $defaults.enable $envoyProxy.enable | eq "true" }}
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy-{{ $node.name }}-svc
  labels:
    fullstack.hedera.com/type: envoy-proxy-svc
    fullstack.hedera.com/node-name: {{ $node.name }}
    fullstack.hedera.com/prometheus-endpoint: active
spec:
  {{- if default $defaults.loadBalancerEnabled $envoyProxy.loadBalancerEnabled | eq "true" }}
  type: LoadBalancer
  {{- end }}
  selector:
    app: envoy-proxy-{{ $node.name }}
  ports:
    - name: hedera-grpc-web
      port: 8080
      targetPort: 8080 # hedera-grpc-web-listener port
    - name: prometheus # port name must be prometheus for prometheus-svc-monitor
      port: 19901
      targetPort: 19901 # prometheus-listener port
{{- end }}
{{- end }}

