{{- range $index, $node := ($.Values.hedera.nodes) }}
{{- $haproxy := $node.haproxy | default dict -}}
{{- $defaults := $.Values.defaults.haproxy }}
{{- if default $defaults.enable $haproxy.enable | eq "true" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-haproxy-{{ $node.name }}-svc
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    fullstack.hedera.com/type: haproxy-svc
    fullstack.hedera.com/node-name: {{ $node.name }}
    fullstack.hedera.com/prometheus-endpoint: active
spec:
  {{- if default $defaults.loadBalancerEnabled $haproxy.loadBalancerEnabled | eq "true" }}
  type: LoadBalancer
  {{- end }}
  selector:
    app: haproxy-{{ $node.name }}
  ports:
    - name: non-tls-grpc-client-port
      port: 50211
      targetPort: 50211
    - name: tls-grpc-client-port
      port: 50212
      targetPort: 50212
    - name: prometheus # port name must be prometheus for prometheus-svc-monitor
      port: 9090
      targetPort: 9090 # stats port
{{- end }}
{{- end }}

