{{ range $nodeConfig := ($.Values.hedera.nodes) }}
---
apiVersion: v1
kind: Service
metadata:
  name: network-{{ $nodeConfig.name }}-svc
  labels:
    fullstack.hedera.com/type: network-node-svc
    fullstack.hedera.com/node-name: {{ $nodeConfig.name }} 
spec:
  selector:
    app: network-{{ $nodeConfig.name }}
  ports:
  - name: gossip
    protocol: TCP
    port: 50111 # gossip port
    targetPort: 50111
  - name: grpc-non-tls
    protocol: TCP
    port: 50211 # non-tls grpc client port
    targetPort: 50211
  - name: grpc-tls
    protocol: TCP
    port: 50212 # tls grpc client port
    targetPort: 50212
  - name: otel-healthcheck
    protocol: TCP
    port: 13133
    targetPort: 13133
  - name: otel-metrics
    protocol: TCP
    port: 8888
    targetPort: 8888
  - name: otel-otlp
    protocol: TCP
    port: 4317
    targetPort: 4317
{{- end }}
