---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: network-node-monitor
  labels:

    team: frontend
spec:
  selector:
    matchLabels:
      fullstack.hedera.com/type: network-node-svc
  endpoints:
    - port: web
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 30900
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: prometheus