{{ range $index, $node := ($.Values.hedera.nodes) }}
{{- $envoyProxy := $node.envoyProxy | default dict -}}
{{- $defaults := $.Values.defaults.haproxy }}
{{- if default $defaults.enable $envoyProxy.enable | eq "true" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy-{{ $node.name }}
spec:
  replicas: {{ default $defaults.replica $envoyProxy.replica }}
  selector:
    matchLabels:
      app: envoy-proxy-{{ $node.name }}
  template:
    metadata:
      labels:
        app: envoy-proxy-{{ $node.name }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: envoy-proxy-cm-{{ $node.name }}
      containers:
      - name: {{ default $defaults.nameOverride $envoyProxy.nameOverride }}
        image: {{ include "container.image" (dict "image" $envoyProxy.image "Chart" $.Chart "defaults" $defaults ) }}
        imagePullPolicy: {{ include "fullstack.images.pullPolicy" (dict "image" $envoyProxy.image "defaults" $defaults) }}
        volumeMounts:
          - name: config-volume
            # https://www.envoyproxy.io/docs/envoy/v1.26.2/start/docker
            mountPath: /etc/envoy
        {{- with default $defaults.resources $envoyProxy.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
{{- end }}
