{{ range $index, $node := ($.Values.hedera.nodes) }}
{{- $envoyProxy := $node.envoyProxy | default $.Values.defaults.envoyProxy -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy-{{ $node.name }}
spec:
  replicas: {{ $envoyProxy.replica }}
  selector:
    matchLabels:
      app: envoy-proxy-{{ $node.name }}
  template:
    metadata:
      labels:
        app: envoy-proxy-{{ $node.name }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: envoy-proxy-cm-{{ $node.name }}
      containers:
      - name: envoy-proxy
        image: {{ include "container.image" (dict "image" $envoyProxy.image "Chart" $.Chart) }}
        imagePullPolicy: {{ include "images.pullPolicy" $envoyProxy.image }}
        volumeMounts:
          - name: config-volume
            # https://www.envoyproxy.io/docs/envoy/v1.26.2/start/docker
            mountPath: /etc/envoy
        {{- with $envoyProxy.resources }}
        resources:
          {{- toYaml . | nindent 4 }}
        {{- end }}
{{- end }}
