{{ range $index, $node := ($.Values.hedera.nodes) }}
{{- $haproxy := $node.haproxy | default $.Values.defaults.haproxy -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-{{ $node.name }}
spec:
  replicas: {{ $haproxy.replica }}
  selector:
    matchLabels:
      app: haproxy-{{ $node.name }}
  template:
    metadata:
      labels:
        app: haproxy-{{ $node.name }}
    spec:
      volumes:
        - name: haproxy-config-volume
          configMap:
            name: haproxy-cm-{{ $node.name }}
        - name: haproxy-ofac-volume
          configMap:
            name: haproxy-ofac-cm
      containers:
      - name: haproxy
        image: {{ include "container.image" (dict "image" $haproxy.image "Chart" $.Chart) }}
        imagePullPolicy: {{ include "images.pullPolicy" $haproxy.image }}
        volumeMounts:
          - name: haproxy-config-volume
            # https://hub.docker.com/_/haproxy/
            mountPath: /usr/local/etc/haproxy
          - name: haproxy-ofac-volume
            mountPath: /var/opt/ofac/
        {{- with $haproxy.resources }}
        resources:
          {{- toYaml . | nindent 4 }}
        {{- end }}
{{- end }}
