{{ range $index, $node := ($.Values.hedera.nodes) }}
{{- $haproxy := $node.haproxy | default dict -}}
{{- $defaults := $.Values.defaults.haproxy }}
{{- if default $defaults.enable $haproxy.enable | eq "true" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-haproxy-{{ $node.name }}
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy-{{ $node.name }}
  template:
    metadata:
      labels:
        app: haproxy-{{ $node.name }}
        fullstack.hedera.com/type: haproxy
    spec:
        {{- if $.Values.deployment.nodeSelector }}
      nodeSelector:
        {{- $.Values.deployment.nodeSelector | toYaml | nindent 8 }}
        {{- end }}
        {{- if $.Values.deployment.tolerations }}
      tolerations:
        {{- $.Values.deployment.tolerations | toYaml | nindent 8 }}
        {{- end }}
        {{- if $.Values.deployment.affinity }}
      affinity:
        {{- $.Values.deployment.affinity | toYaml | nindent 8 }}
        {{- end }}
        {{- if $.Values.deployment.priorityClassName }}
      priorityClassName: {{ $.Values.deployment.priorityClassName }}
        {{- end }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      volumes:
        - name: haproxy-config-volume
          configMap:
            name: {{ $.Release.Name }}-haproxy-cm-{{ $node.name }}
        - name: haproxy-ofac-volume
          configMap:
            name: {{ $.Release.Name }}-haproxy-ofac-cm
      containers:
      - name: {{ default $defaults.nameOverride $haproxy.nameOverride }}
        image: {{ include "fullstack.container.image" (dict "image" $haproxy.image "Chart" $.Chart "defaults" $defaults ) }}
        imagePullPolicy: {{ include "fullstack.images.pullPolicy" (dict "image" $haproxy.image "defaults" $defaults )  }}
        volumeMounts:
          - name: haproxy-config-volume
            # https://hub.docker.com/_/haproxy/
            mountPath: /usr/local/etc/haproxy
          - name: haproxy-ofac-volume
            mountPath: /var/opt/ofac/
        {{- with default $defaults.resources $haproxy.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
{{- end }}

