{{ range $index, $node := ($.Values.hedera.nodes) }}
{{- $haproxy := $node.haproxy | default $.Values.defaults.haproxy -}}
{{- $defaults := $.Values.defaults.haproxy }}
{{- if $haproxy.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-{{ $node.name }}
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy-{{ $node.name }}
  template:
    metadata:
      labels:
        app: haproxy-{{ $node.name }}
        fullstack.hedera.com/type: haproxy
        {{- include "fullstack.testLabels" $ | nindent 8 }}
    spec:
        {{- if $.Values.deployment.nodeSelector }}
      nodeSelector:
        {{- $.Values.deployment.nodeSelector | toYaml | nindent 8 }}
        {{- end }}
        {{- if $.Values.deployment.tolerations }}
      tolerations:
        {{- $.Values.deployment.tolerations | toYaml | nindent 8 }}
        {{- end }}
        {{- if $.Values.deployment.affinity }}
      affinity:
        {{- $.Values.deployment.affinity | toYaml | nindent 8 }}
        {{- end }}
        {{- if $.Values.deployment.priorityClassName }}
      priorityClassName: {{ $.Values.deployment.priorityClassName }}
        {{- end }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      volumes:
        - name: haproxy-config-volume
          emptyDir: {}
        - name: haproxy-configmap-volume
          configMap:
            name: haproxy-cm-{{ $node.name }}
        - name: haproxy-ofac-volume
          configMap:
            name: haproxy-ofac-cm
      containers:
      - name: {{ default $defaults.nameOverride $haproxy.nameOverride }}
        image: {{ include "fullstack.container.image" (dict "image" $haproxy.image "Chart" $.Chart "defaults" $defaults ) }}
        imagePullPolicy: {{ include "fullstack.images.pullPolicy" (dict "image" $haproxy.image "defaults" $defaults )  }}
        envFrom:
          - secretRef:
              name: haproxy-secrets
        livenessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - |
                rm -f livenessProbe.json || true
                wget -q -O livenessProbe.json --header 'content-type: application/json' http://dataplane:${HAPROXY_PASSWORD}@0.0.0.0:5555/v2/services/haproxy/stats/native?type=backend || return 1
        readinessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - |
                rm -f readinessProbe.json || true
                wget -q -O readinessProbe.json --header 'content-type: application/json' http://dataplane:${HAPROXY_PASSWORD}@0.0.0.0:5555/v2/services/haproxy/stats/native?type=backend || return 1
        startupProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - |
              jq_check() {
                jq --version > /dev/null 2>&1 && return
                echo "jq not found, installing jq"
                apk add jq || return 1
              }
              probe() {
                jq_check || return 1
                wget -q -O response.json --header 'content-type: application/json' http://dataplane:${HAPROXY_PASSWORD}@0.0.0.0:5555/v2/services/haproxy/stats/native?type=backend || return 1
                BACKEND_STATUS=$(jq -r '.[] | .stats[] | select(.name == "http_backend") | .stats.status' < response.json)
                echo "http_backend status: $BACKEND_STATUS"
                if [ "$BACKEND_STATUS" = "UP" ]; then
                  return 0
                else
                  return 1
                fi
              }
              probe
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 720
        volumeMounts:
          - name: haproxy-config-volume
            # https://hub.docker.com/_/haproxy/
            mountPath: /usr/local/etc/haproxy
          - name: haproxy-configmap-volume
            # https://hub.docker.com/_/haproxy/
            mountPath: /usr/local/etc/haproxy/haproxy.cfg
            subPath: haproxy.cfg
          - name: haproxy-ofac-volume
            mountPath: /var/opt/
        {{- with default $defaults.resources $haproxy.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
{{- end }}
