{{- if $.Values.gatewayApi.gateway.enabled | eq "true" }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy-config
spec:
  {{- if  $.Values.gatewayApi.gateway.loadBalancerEnabled }}
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        loadBalancerIP: {{ $.Values.gatewayApi.gateway.loadBalancerIP }}
  {{- end }}
{{- end }}
