{{- if $.Values.gatewayApi.gateway.enabled | eq "true" }}
{{- if  $.Values.gatewayApi.gateway.loadBalancerEnabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: EnvoyProxy
metadata:
  name: {{ $.Values.gatewayApi.gateway.name }}-proxy
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        loadBalancerIP: {{ $.Values.gatewayApi.gateway.loadBalancerIP }}
{{- end }}
{{- end }}
