apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hedera-explorer-route
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    fullstack.hedera.com/type: http-route
    {{- include "fullstack.testLabels" $ | nindent 4 }}
spec:
  parentRefs:
    - name: fst
      sectionName: hedera-explorer
  rules:
    - backendRefs:
      - name: {{ .Release.Name }}-hedera-explorer
        port: 80
