kubernetesClusterDomain: cluster.local
prometheusOperator:
  nodeSelector:
    kubernetes.io/os: linux
  ports:
  - name: http
    port: 8080
    targetPort: http
  prometheusOperator:
    args:
    - --kubelet-service=kube-system/kubelet
    - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.67.1
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    image:
      repository: quay.io/prometheus-operator/prometheus-operator
      tag: v0.67.1
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
  replicas: 1
  serviceAccount:
    annotations: {}
  type: ClusterIP
