
{{ range $node := ($.Values.hedera.nodes) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: network-{{ $node.name }}
  labels:
    app: network-{{ $node.name }}
spec:
  replicas: 1
  serviceName: "network-node-{{ $node.name }}"
  selector:
    matchLabels:
      app: network-{{ $node.name }}
  template:
    metadata:
      labels:
        app: network-{{ $node.name }}
    spec:
      volumes:
        - name: hedera-storage
          emptyDir: {}

      containers:
      - name: root-container
        image: {{ $.Values.infrastructure.docker.registry }}/{{ $.Values.infrastructure.docker.images.root }}
        resources:
          requests:
            cpu: {{ $node.requests.cpu }}
            memory: {{ $node.requests.memory }}
          limits:
            cpu: {{ $node.limits.cpu }}
            memory: {{ $node.limits.memory }}
        volumeMounts:
          - name: hedera-storage
            mountPath: /opt/hgcapp/

  {{ if $node.uploaderSidecars }}

      # Account Balance Uploader
      - name: account-balances-uploader
        image: {{ $.Values.infrastructure.docker.images.mirroruploader }}
        securityContext:
          runAsUser: {{ $.Values.mirror.user }}
        command:
          - /usr/bin/env
          - python3.7
          - /usr/local/bin/mirror.py
          - --linux
          - --watch-directory
          - {{ $.Values.mirror.accountBalance.watchDir }}
        volumeMounts:
          - name: hedera-storage
            mountPath: /opt/hgcapp/
        envFrom:
          - configMapRef:
                name: uploader-config
          - secretRef:
              name: uploader-secrets

        # Event Stream Uploader
      - name: event-stream-uploader
        image: {{ $.Values.infrastructure.docker.images.mirroruploader }}
        securityContext:
          runAsUser: {{ $.Values.mirror.user }}
        command:
          - /usr/bin/env
          - python3.7
          - /usr/local/bin/mirror.py
          - --linux
          - --watch-directory
          - {{ $.Values.mirror.eventStream.watchDir }}
        volumeMounts:
          - name: hedera-storage
            mountPath: /opt/hgcapp/
        envFrom:
          - configMapRef:
              name: uploader-config
          - secretRef:
              name: uploader-secrets

        # Record Stream Uploader
      - name: record-stream-uploader
        image: {{ $.Values.infrastructure.docker.images.mirroruploader }}
        securityContext:
          runAsUser: {{ $.Values.mirror.user }}
        command:
          - /usr/bin/env
          - python3.7
          - /usr/local/bin/mirror.py
          - --linux
          - --watch-directory
          - {{ $.Values.mirror.recordStream.watchDir }}
          - --csv-stats-directory
          - {{ $.Values.mirror.recordStream.csvStatsDir }}
        volumeMounts:
          - name: hedera-storage
            mountPath: /opt/hgcapp/
        envFrom:
          - configMapRef:
              name: uploader-config
          - secretRef:
              name: uploader-secrets

      # Record Stream Sidecar Uploader
      - name: record-sidecar-uploader
        image: {{ $.Values.infrastructure.docker.images.mirroruploader }}
        securityContext:
          runAsUser: {{ $.Values.mirror.user }}
        command:
          - /usr/bin/env
          - python3.7
          - /usr/local/bin/mirror.py
          - --linux
          - --watch-directory
          - {{ $.Values.mirror.recordStreamSideCar.watchDir }}
        volumeMounts:
          - name: hedera-storage
            mountPath: /opt/hgcapp/
        envFrom:
          - configMapRef:
              name: uploader-config
          - secretRef:
              name: uploader-secrets
  {{ end }}

{{ end }}