
{{ range $node := ($.Values.hedera.nodes) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: network-{{ $node.name }}
  labels:
    app: network-{{ $node.name }}
spec:
  replicas: 1
  serviceName: "network-node-{{ $node.name }}"
  selector:
    matchLabels:
      app: network-{{ $node.name }}
  template:
    metadata:
      labels:
        app: network-{{ $node.name }}
    spec:
      volumes:
        - name: hgcapp-dir # /opt/hgcapp
          emptyDir: {}
        - name: hedera-account-balances # /opt/hgcapp/accountbalance
          emptyDir: {}
        - name: hedera-event-streams # /opt/hgcapp/events
          emptyDir: {}
        - name: hedera-record-streams # /opt/hgcapp/recordstreams
          emptyDir: {}
        - name: hedera-sidecar # /opt/hgcapp/sidecar
          emptyDir: {}
        {{- if $.Values.sidecars.otel.enabled }}
        - name: otel-collector-config
          configMap:
            name: otel-collector-config
        {{- end }}
      containers:
      - name: root-container
        image: {{ $.Values.infrastructure.docker.images.root }}
        command: [ "/bin/sh" ]
        args: [ "-c", "while true; do echo root:heartbeat; sleep 10;done" ]
        resources:
          requests:
            cpu: {{ $node.requests.cpu }}
            memory: {{ $node.requests.memory }}
          limits:
            cpu: {{ $node.limits.cpu }}
            memory: {{ $node.limits.memory }}
        volumeMounts:
          - name: hgcapp-dir
            mountPath: /opt/hgcapp/

  {{- if $node.uploaderSidecars }}

      # Account Balance Uploader
      - name: account-balances-uploader
        image: {{ $.Values.infrastructure.docker.images.mirroruploader }}
        securityContext:
          runAsUser: {{ $.Values.mirror.user }}
        command:
          - /usr/bin/env
          - python3.7
          - /usr/local/bin/mirror.py
          - --linux
          - --watch-directory
          - {{ $.Values.mirror.accountBalance.watchDir }}
        volumeMounts:
          - name: hedera-account-balances
            mountPath: /opt/hgcapp/accountbalance
        envFrom:
          - configMapRef:
                name: account-balance-uploader-config
          - secretRef:
              name: uploader-secrets

        # Event Stream Uploader
      - name: event-stream-uploader
        image: {{ $.Values.infrastructure.docker.images.mirroruploader }}
        securityContext:
          runAsUser: {{ $.Values.mirror.user }}
        command:
          - /usr/bin/env
          - python3.7
          - /usr/local/bin/mirror.py
          - --linux
          - --watch-directory
          - {{ $.Values.mirror.eventStream.watchDir }}
        volumeMounts:
          - name: hedera-event-streams
            mountPath: /opt/hgcapp/events
        envFrom:
          - configMapRef:
              name: event-stream-uploader-config
          - secretRef:
              name: uploader-secrets

        # Record Stream Uploader
      - name: record-stream-uploader
        image: {{ $.Values.infrastructure.docker.images.mirroruploader }}
        securityContext:
          runAsUser: {{ $.Values.mirror.user }}
        command:
          - /usr/bin/env
          - python3.7
          - /usr/local/bin/mirror.py
          - --linux
          - --watch-directory
          - {{ $.Values.mirror.recordStream.watchDir }}
          - --csv-stats-directory
          - {{ $.Values.mirror.recordStream.csvStatsDir }}
        volumeMounts:
          - name: hedera-record-streams
            mountPath: /opt/hgcapp/recordstream
        envFrom:
          - configMapRef:
              name: record-stream-uploader-config
          - secretRef:
              name: uploader-secrets

      # Record Stream Sidecar Uploader
      - name: record-sidecar-uploader
        image: {{ $.Values.infrastructure.docker.images.mirroruploader }}
        securityContext:
          runAsUser: {{ $.Values.mirror.user }}
        command:
          - /usr/bin/env
          - python3.7
          - /usr/local/bin/mirror.py
          - --linux
          - --watch-directory
          - {{ $.Values.mirror.recordStreamSideCar.watchDir }}
        volumeMounts:
          - name: hedera-sidecar
            mountPath: /opt/hgcapp/sidecar
        envFrom:
          - configMapRef:
              name: record-stream-sidecar-config
          - secretRef:
              name: uploader-secrets
  {{ end }}

  {{ if $.Values.sidecars.otel.enabled }}

      # OTel collector side car
      {{- include "sidecars.otel-collector" $ | nindent 6 }}
  {{ end }}

{{ end }}
