
{{ range $index, $node := $.Values.hedera.nodes }}
{{- $root := $node.root | default $.Values.defaults.root -}}
{{- $recordStream := ($node.sidecars).recordStreamUploader | default $.Values.defaults.sidecars.recordStreamUploader -}}
{{- $eventStream := ($node.sidecars).eventStreamUploader | default $.Values.defaults.sidecars.eventStreamUploader -}}
{{- $balanceUploader := ($node.sidecars).accountBalanceUploader | default $.Values.defaults.sidecars.accountBalanceUploader -}}
{{- $backupUploader := ($node.sidecars).backupUploader | default $.Values.defaults.sidecars.backupUploader -}}
{{- $otelCollector := ($node.sidecars).otelCollector | default $.Values.defaults.sidecars.otelCollector -}}
{{- $resources := $node.resources | default $.Values.defaults.resources }}
{{- $cloud := $.Values.cloud }}
{{- $defaults := $.Values.defaults }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: network-{{ $node.name }}
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    app: network-{{ $node.name }}
  {{- if $.Values.deployment.podLabels }}
    {{- $.Values.deployment.podLabels | toYaml | nindent 4 }}
  {{- end }}
  {{- if $.Values.deployment.podAnnotations }}
  annotations:
    {{- $.Values.deployment.podAnnotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  serviceName: "network-{{ $node.name }}"
  selector:
    matchLabels:
      app: network-{{ $node.name }}
  template:
    metadata:
      labels:
        app: network-{{ $node.name }}
        fullstack.hedera.com/type: network-node
        fullstack.hedera.com/node-name: {{ $node.name }}
    spec:
      {{- if $.Values.deployment.nodeSelectors }}
      nodeSelector:
      {{- $.Values.deployment.nodeSelectors | toYaml | nindent 8 }}
      {{- end }}
      {{- if $.Values.deployment.tolerations }}
      tolerations:
      {{- $.Values.deployment.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if $.Values.deployment.affinity }}
      affinity:
      {{- $.Values.deployment.affinity | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      volumes:
        - name: hgcapp-storage # change me
          emptyDir: {}
        {{- if default $defaults.sidecars.otelCollector.enable  $otelCollector.enable | eq "true" }}
        - name: otel-collector-volume
          configMap:
            name: otel-collector-cm
        {{- end }}
      initContainers:
      # Init Container
      - name: init-container
        image: {{ include "fullstack.container.image" (dict "image" $root.image "Chart" $.Chart "defaults" $root) }}
        imagePullPolicy: {{ include "fullstack.images.pullPolicy" (dict "image" $root.image "defaults" $root) }}
        command: [ "/bin/sh", "-c", "mkdir -p /opt/hgcapp/hedera-backups /opt/hgcapp/accountBalances /opt/hgcapp/events /opt/hgcapp/recordStreams /opt/hgcapp/sidecar /opt/hgcapp/recordStreams/uploader-stats/" ]
        securityContext:
          {{- include "fullstack.hedera.security.context" . | nindent 10 }}
        volumeMounts:
          - name: hgcapp-storage
            mountPath: /opt/hgcapp/
      containers:
      # Root Container
      - name: {{ $root.nameOverride | default "root-container" }}
        image: {{ include "fullstack.container.image" (dict "image" $root.image "Chart" $.Chart "defaults" $root) }}
        imagePullPolicy: {{ include "fullstack.images.pullPolicy" (dict "image" $root.image "defaults" $root) }}
        securityContext: # need to run as root with privileged mode
          {{- include "fullstack.root.security.context.privileged" . | nindent 10 }}
        {{- with $resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: hgcapp-storage
            mountPath: /opt/hgcapp/
        env:
          {{- include "fullstack.defaultEnvVars" . | nindent 10 }}
      # Sidecars
      {{- include "fullstack.sidecars" (dict
        "recordStream" $recordStream
        "backupUploader" $backupUploader
        "balanceUploader" $balanceUploader
        "eventStream" $eventStream
        "recordStream" $recordStream
        "otelCollector" $otelCollector
        "cloud" $.Values.cloud
        "chart" $.Chart
        "node" $node
        "defaults" $defaults
        "minioserver" (index $.Values "minio-server")
        ) | nindent 6 }}
{{ end }}
