
{{ range $node := ($.Values.hedera.nodes) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: network-{{ $node.name }}
  labels:
    app: network-{{ $node.name }}
spec:
  replicas: 1
  serviceName: "network-{{ $node.name }}"
  selector:
    matchLabels:
      app: network-{{ $node.name }}
  template:
    metadata:
      labels:
        app: network-{{ $node.name }}
        type: network-node
    spec:
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      volumes:
        - name: hgcapp-storage # change me
          emptyDir: {}
        {{- if $node.sidecars.otel }}
        - name: otel-collector-config
          configMap:
            name: otel-collector-config
        {{- end }}
      initContainers:
      - name: init-container
        image: {{ $.Values.infrastructure.docker.images.root }}
        command: [ "/bin/sh", "-c", "mkdir /opt/hgcapp/hedera-backups /opt/hgcapp/accountbalance /opt/hgcapp/events /opt/hgcapp/recordstream /opt/hgcapp/sidecar /opt/hgcapp/recordstream/uploader-stats/"  ]
        {{- include "hedera.security.context" . | nindent 8}}
        volumeMounts:
          - name: hgcapp-storage
            mountPath: /opt/hgcapp/
      containers:
      - name: root-container
        image: {{ $.Values.infrastructure.docker.images.root }}
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          privileged: true
        resources:
          requests:
            cpu: {{ $node.requests.cpu }}
            memory: {{ $node.requests.memory }}
          limits:
            cpu: {{ $node.limits.cpu }}
            memory: {{ $node.limits.memory }}
        volumeMounts:
          - name: hgcapp-storage
            mountPath: /opt/hgcapp/
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

  {{- if $node.sidecars.accountBalancesUploader }}
      # Account Balance Uploader
      - name: account-balances-uploader
        image: {{ $.Values.infrastructure.docker.images.mirroruploader }}
        {{- include "hedera.security.context" . | nindent 8 }}
        command:
          - /usr/bin/env
          - python3.7
          - /usr/local/bin/mirror.py
          - --linux
          - --watch-directory
          - {{ $.Values.mirror.accountBalance.watchDir }}
        volumeMounts:
          - name: hgcapp-storage
            mountPath: /opt/hgcapp/
        envFrom:
          - configMapRef:
                name: account-balance-uploader-config
          - secretRef:
              name: uploader-secrets
  {{- end }}

  {{- if $node.sidecars.eventStreamUploader }}
      # Event Stream Uploader
      - name: event-stream-uploader
        image: {{ $.Values.infrastructure.docker.images.mirroruploader }}
        {{- include "hedera.security.context" . | nindent 8 }}
        command:
          - /usr/bin/env
          - python3.7
          - /usr/local/bin/mirror.py
          - --linux
          - --watch-directory
          - {{ $.Values.mirror.eventStream.watchDir }}
        volumeMounts:
          - name: hgcapp-storage
            mountPath: /opt/hgcapp/
        envFrom:
          - configMapRef:
              name: event-stream-uploader-config
          - secretRef:
              name: uploader-secrets
  {{- end }}

  {{- if $node.sidecars.recordStreamUploader }}
      # Record Stream Uploader
      - name: record-stream-uploader
        image: {{ $.Values.infrastructure.docker.images.mirroruploader }}
        {{- include "hedera.security.context" . | nindent 8 }}
        command:
          - /usr/bin/env
          - python3.7
          - /usr/local/bin/mirror.py
          - --linux
          - --watch-directory
          - {{ $.Values.mirror.recordStream.watchDir }}
          - --csv-stats-directory
          - {{ $.Values.mirror.recordStream.csvStatsDir }}
        volumeMounts:
          - name: hgcapp-storage
            mountPath: /opt/hgcapp/
        envFrom:
          - configMapRef:
              name: record-stream-uploader-config
          - secretRef:
              name: uploader-secrets
  {{- end }}

  {{- if $node.sidecars.recordSidecarUploader }}
      # Record Stream Sidecar Uploader
      - name: record-sidecar-uploader
        image: {{ $.Values.infrastructure.docker.images.mirroruploader }}
        {{- include "hedera.security.context" . | nindent 8 }}
        command:
          - /usr/bin/env
          - python3.7
          - /usr/local/bin/mirror.py
          - --linux
          - --watch-directory
          - {{ $.Values.mirror.recordStreamSideCar.watchDir }}
        volumeMounts:
          - name: hgcapp-storage
            mountPath: /opt/hgcapp/
        envFrom:
          - configMapRef:
              name: record-stream-uploader-config
          - secretRef:
              name: uploader-secrets
  {{- end }}

  {{- if $node.sidecars.otel }}
      # OTel collector side car
      {{- include "sidecars.otel-collector" $ | nindent 6 }}
  {{- end }}

  {{- if $node.sidecars.backupUploader }}
      # Backup Uploader
      - name: backup-uploader
        image: {{ $.Values.infrastructure.docker.images.backupUploader }}
        {{- include "hedera.security.context" . | nindent 8 }}
        volumeMounts:
          - name: hgcapp-storage
            mountPath: /opt/hgcapp/
            readOnly: true
        envFrom:
          - configMapRef:
              name: backup-config
          - secretRef:
              name: backup-secrets
  {{- end }}
{{ end }}
