apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-monitoring-role
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules:
  - apiGroups: [ "" ]
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
  - apiGroups: [ "" ]
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-monitoring-role-binding
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
subjects:
  - kind: ServiceAccount
    name: tester
roleRef:
  kind: Role
  name: pod-monitor
  apiGroup: rbac.authorization.k8s.io