apiVersion: v1
kind: Secret
metadata:
  name: uploader-mirror-secrets
type: Opaque
data:
  # add your secrets here
  # Note: Kubernetes secrets should be base64 encoded
  secret1: "c2VjcmV0"
  secret2: "c2VjcmV0"
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-secrets
type: Opaque
data:
  # add your secrets here
  # Note: Kubernetes secrets should be base64 encoded
  secret1: "c2VjcmV0"
  secret2: "c2VjcmV0"
