apiVersion: v1
kind: Secret
metadata:
  name: uploader-secrets
type: Opaque
data: # TODO: These secrets should be got from minio secrets
  S3_ACCESS_KEY: ""
  S3_SECRET_KEY: ""
  GCS_ACCESS_KEY: ""
  GCS_SECRET_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-secrets
type: Opaque
data:
  # add your secrets here
  # Note: Kubernetes secrets should be base64 encoded
  secret1: "c2VjcmV0"
  secret2: "c2VjcmV0"
