{{ range $nodeConfig := ($.Values.hedera.nodes) }}
---
apiVersion: v1
kind: Service
metadata:
  name: network-{{ $nodeConfig.name }}-service
spec:
  selector:
    app: network-{{ $nodeConfig.name }}
  ports:
  - protocol: TCP
    port: 50211
    targetPort: 50211
{{- end }}
