apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-monitoring-role
rules:
  - apiGroups: [ "" ]
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
  - apiGroups: [ "" ]
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-monitoring-role-binding
subjects:
  - kind: ServiceAccount
    name: tester
roleRef:
  kind: Role
  name: pod-monitor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tester-cfg
data:
  test.sh: |
    {{- .Files.Get "configs/test.sh" | nindent 4 }}
