apiVersion: v1
kind: ServiceAccount
metadata:
  name: tester
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tester-role
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tester-role-binding
subjects:
  - kind: ServiceAccount
    name: tester
roleRef:
  kind: Role
  name: tester-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tester-cfg
data:
  test.sh: |
    {{- .Files.Get "configs/test.sh" | nindent 4 }}
