package com.hedera.fullstack.model;

public enum Component {
    NODE_SOFTWARE_POD,

    // This could be better nested, but this may be the right abstraction we need
    NODE_SOFTWARE_POD_SIDECAR_STATE_BACKUP_UPLOADER,
    NODE_SOFTWARE_POD_SIDECAR_RECORD_STREAM_UPLOADER,
    NODE_SOFTWARE_POD_SIDECAR_SIDECAR_STREAM_UPLOADER,
    NODE_SOFTWARE_POD_SIDECAR_POST_CONSENSUS_UPLOADER,

    MINIO_DEPLOYMENT,

    MIRROR_NODE_DEPLOYMENT_IMPORTER,
    MIRROR_NODE_DEPLOYMENT_REST_API,
    MIRROR_NODE_DEPLOYMENT_DATABASE,
    MIRROR_NODE_DEPLOYMENT_REDIS,
    MIRROR_NODE_EXPLORER,
    JSON_RPC_RELAY,
    ENVOY_PROXY,
    HAPROXY,
}

