{{- $previous := lookup "v1" "ConfigMap" .Release.Namespace "haproxy-cm-{{ $node.name }}" }}
# Create a haproxy configmap for each network node
# This will change in the future, we plan create a haproxy for a given network node only if specified in the config
{{- $random_user := randAlpha 10  -}}
{{- $random_password := randAlpha 10  -}}
{{- range $index, $node := ($.Values.hedera.nodes) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-cm-{{ $node.name }}
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    {{- include "fullstack.testLabels" $ | nindent 4 }}
data:
  haproxy.cfg: |
    {{- tpl ($.Files.Get "config-files/haproxy.cfg") (dict "nodeConfig" $node "namespace" $.Release.Namespace "haproxy_user" $random_user "haproxy_password" $random_password "Template" $.Template) | nindent 4 }}
---
{{ end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ofac-cm
data:
  ofacBlock.acl: |
    {{- .Files.Get "config-files/ofacBlock.acl" | nindent 4  }}
