{{- if or $.Values.hedera.configMaps.apiPermissionsProperties $.Values.hedera.configMaps.applicationProperties $.Values.hedera.configMaps.bootstrapProperties }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-node-data-config-cm
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    {{- include "fullstack.testLabels" $ | nindent 4 }}
data:
{{- if $.Values.hedera.configMaps.apiPermissionsProperties }}
  api-permission.properties: {{ toYaml .Values.hedera.configMaps.apiPermissionsProperties | indent 4 }}
{{- end }}
{{- if $.Values.hedera.configMaps.applicationProperties }}
  application.properties: {{ toYaml .Values.hedera.configMaps.applicationProperties  | indent 4 }}
{{- end }}
{{- if $.Values.hedera.configMaps.bootstrapProperties }}
  bootstrap.properties: {{ toYaml .Values.hedera.configMaps.bootstrapProperties  | indent 4 }}
{{- end }}
{{- end }}
