apiVersion: v1
kind: ConfigMap
metadata:
  name: network-node-hapi-app-cm
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    {{- include "fullstack.testLabels" $ | nindent 4 }}
data:
  applicationEnv: |
    {{ .Values.hedera.configMaps.applicationEnv }}
  configTxt: |
    {{ .Values.hedera.configMaps.configTxt }}
  log4j2Xml: |
    {{ .Values.hedera.configMaps.log4j2Xml }}
  settingsTxt: |
    {{ .Values.hedera.configMaps.settingsTxt }}
  settingsUsedTxt: |
    {{ .Values.hedera.configMaps.settingsUsedTxt }}
