{{- if or $.Values.hedera.configMaps.configTxt $.Values.hedera.configMaps.log4j2Xml $.Values.hedera.configMaps.settingsTxt }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-node-hapi-app-cm
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    {{- include "fullstack.testLabels" $ | nindent 4 }}
data:
{{- if $.Values.hedera.configMaps.configTxt }}
  config.txt: {{ toYaml .Values.hedera.configMaps.configTxt  | indent 4 }}
{{- end }}
{{- if $.Values.hedera.configMaps.log4j2Xml }}
  log4j2.xml: {{ toYaml .Values.hedera.configMaps.log4j2Xml  | indent 4 }}
{{- end }}
{{- if $.Values.hedera.configMaps.settingsTxt }}
  settings.txt: {{ toYaml .Values.hedera.configMaps.settingsTxt  | indent 4 }}
{{- end }}
{{- end }}
