{{- if $.Values.hedera.configMaps.applicationEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-node-etc-cm
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    {{- include "fullstack.testLabels" $ | nindent 4 }}
data:
{{- if $.Values.hedera.configMaps.applicationEnv }}
  application.env: {{ toYaml .Values.hedera.configMaps.applicationEnv  | indent 4 }}
{{- end }}
{{- end }}
