apiVersion: v1
kind: ConfigMap
metadata:
  name: network-node-data-config-cm
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    {{- include "fullstack.testLabels" $ | nindent 4 }}
data:
  api-permission.properties: |
{{ .Values.hedera.configMaps.apiPermissionsProperties | nindent 4 }}
  application.properties: |
{{ .Values.hedera.configMaps.applicationProperties | nindent 4 }}
  bootstrap.properties: |
{{ .Values.hedera.configMaps.bootstrapProperties | nindent 4 }}
