apiVersion: v1
kind: ConfigMap
metadata:
  name: network-node-hapi-app-cm
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    {{- include "fullstack.testLabels" $ | nindent 4 }}
data:
  configTxt: |
    {{ .Values.hedera.configMaps.configTxt | nindent 4 }}
  log4j2Xml: |
    {{ .Values.hedera.configMaps.log4j2Xml | nindent 4 }}
  settingsTxt: |
    {{ .Values.hedera.configMaps.settingsTxt | nindent 4 }}
  settingsUsedTxt: |
    {{ .Values.hedera.configMaps.settingsUsedTxt | nindent 4 }}
