{{- range $index, $node := ($.Values.hedera.nodes) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-cm-{{ $node.name }}
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    {{- include "fullstack.testLabels" $ | nindent 4 }}
data:
  config.yaml: |
  {{- $params := dict "" "" -}}
  {{- $_ignore := set $params "otelDefaults" $.Values.defaults.sidecars.otelCollector  -}}
  {{- $_ignore = set $params "Template" $.Template -}}
  {{- $_ignore = set $params "environment_name" $.Release.Namespace -}}
  {{- $_ignore = set $params "otel_node_id" $index -}}
  {{- $_ignore = set $params "otel_instance_type" "hedera-node" -}}
  {{- tpl ( $.Files.Get "config-files/otel-collector-config.yaml" ) $params | nindent 4 }}
---
{{ end }}
