{{- if $.Values.telemetry.prometheus.svcMonitor.enable | eq "true" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: network-node-monitor
  labels:
    fullstack.hedera.com/type: network-node-svc-monitor
spec:
  selector:
    matchLabels:
      fullstack.hedera.com/type: network-node-svc
  endpoints:
    - port: prometheus # must match the prometheus port-name in network-node-svc.yaml
      interval: 10s # ideally it should be higher than the node-metrics-scraper interval set in otel-collector-config.yaml
{{- end }}
